# Generated by Django 4.0.2 on 2022-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extractsentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_id', models.IntegerField(default=0)),
                ('result_sentence', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('LoaiHinh', models.CharField(blank=True, max_length=200)),
                ('TacGia', models.CharField(blank=True, max_length=200)),
                ('SoDienThoai', models.CharField(blank=True, max_length=30)),
                ('Gia', models.CharField(blank=True, max_length=200)),
                ('DienTich', models.CharField(blank=True, max_length=200, null=True)),
                ('DiaChi', models.CharField(blank=True, max_length=200)),
                ('ChungNhanSoHuu', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
    ]
