# Generated by Django 4.0.1 on 2022-09-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='ChungNhanSoHuu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='DiaChi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='houses',
            name='DienTich',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Gia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='houses',
            name='LoaiHinh',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='houses',
            name='SoDienThoai',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='houses',
            name='TacGia',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
