# Generated by Django 4.0.2 on 2022-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook_Post_Job_Scraper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=191)),
                ('post_id', models.CharField(max_length=191)),
                ('post_user_id', models.CharField(max_length=191)),
                ('post_message', models.TextField(null=True)),
                ('post_image_link', models.TextField(null=True)),
                ('post_image_alt', models.TextField(null=True)),
                ('post_total_reactions', models.BigIntegerField(default=0)),
                ('post_total_comments', models.BigIntegerField(default=0)),
                ('post_total_shares', models.BigIntegerField(default=0)),
                ('timestamp', models.FloatField(default=1659712287.162961)),
                ('created_at', models.FloatField(default=1659712287.162971)),
                ('updated_at', models.FloatField(default=1659712287.162977)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Facebook_User_Profile_Job_Scraper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.CharField(max_length=191)),
                ('group_id', models.CharField(max_length=191)),
                ('user_id_job', models.BigIntegerField(default=None)),
                ('user_name_job', models.CharField(default='-1', max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('work', models.CharField(default=None, max_length=500)),
                ('education', models.CharField(default=None, max_length=500)),
                ('friend_count', models.IntegerField(default=None, null=True)),
                ('follower_count', models.IntegerField(default=None, null=True)),
                ('following_count', models.IntegerField(default=None, null=True)),
                ('cover_photo', models.CharField(default=None, max_length=500, null=True)),
                ('profile_picture', models.CharField(default=None, max_length=500, null=True)),
                ('created_at', models.FloatField(default=1659712287.163464)),
                ('updated_at', models.FloatField(default=1659712287.163471)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='facebook_user_profile_job_scraper',
            constraint=models.UniqueConstraint(fields=('user_id_job',), name='facebook user id job'),
        ),
        migrations.AddConstraint(
            model_name='facebook_user_profile_job_scraper',
            constraint=models.UniqueConstraint(fields=('user_name_job',), name='facebook username job'),
        ),
    ]
